### ISSUE TITLE
Pattern Refiller card doesn't work on encoding pattern

### ISSUE THREAD

**Issue by Zedhard** [ko-lja/expandedae#34]
Blank patterns doesn't refill when i encode recipes. Tried in both universal terminal and expanded. 

Modpack is FTB Evolution. 
Mod version 2.1.0

**Comment by Zedhard** [comment]
Seems to be related with playing on dedicated server. Works fine in singleplayer.

**Comment by ko-lja** [comment]
Sorry completely forgot about this, i know what the issue is. Will fix soon

**Comment by themidnightshadow12-ship-it** [comment]
Any update on this? Playing Star Technology 1.20.1 and the pattern refiller card doesn't refill any patterns in the universal terminal.

**Comment by ko-lja** [comment]
Sorry, forgot to close this issue. It was fixed in a13b3078f34150acd2a3c5dd45f933f88de14d86

**Comment by ko-lja** [comment]
> Any update on this? Playing Star Technology 1.20.1 and the pattern refiller card doesn't refill any patterns in the universal terminal.

StarT is a few versions behind, try updating to latest

**Comment by Zedhard** [comment]
What about 1.21.1? Haven't seen any updates on that version.

**Comment by ko-lja** [comment]
> What about 1.21.1? Haven't seen any updates on that version.

I'll make an update in the coming days to give 1.21.1 the same features as 1.20.1

**Comment by themidnightshadow12-ship-it** [comment]
I have updated expanded ae to the latest version, however the refiller card still does not work.
